In [1]:
a= [1,2,3]
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

* di python untuk melakukan operasi numerical menggunakan package numpy

In [2]:
import numpy as np

In [3]:
a= [1,2,4]

In [4]:
b= np.array(a)

In [5]:
b*3

array([ 3,  6, 12])

In [6]:
np.sum(a)

7

In [7]:
np.std(a)

1.247219128924647

In [8]:
np.mean(a)

2.3333333333333335

In [10]:
np.around(a)

array([1, 2, 4])

In [ ]:
np.sqrt()

In [13]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [16]:
np.logspace(-1,1,10)

array([ 0.1       ,  0.16681005,  0.27825594,  0.46415888,  0.77426368,
        1.29154967,  2.15443469,  3.59381366,  5.9948425 , 10.        ])

In [17]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

control randomness

In [78]:
state = np.random.RandomState(42)

In [140]:
state.rand(2)

array([0.31800347, 0.11005192])