# print

In [1]:
print("hallo, nama saya rahmat")

hallo, nama saya rahmat


In [2]:
print('hallo, nama saya rahmat')

hallo, nama saya rahmat


In [3]:
print("""hallo, nama saya rahm"at""")

hallo, nama saya rahm"at


# variable

In [4]:
a = 1

In [5]:
a

1

In [6]:
a, b = 4, 5

In [7]:
a

4

In [8]:
b

5

In [9]:
a,b

(4, 5)

# list

In [10]:
a = [1, 2, 4, "empat", "lima"]

In [11]:
a

[1, 2, 4, 'empat', 'lima']

In [12]:
a[0]

1

In [13]:
a[1]

2

In [14]:
a[-1]

'lima'

In [15]:
a.append(4)

In [16]:
a

[1, 2, 4, 'empat', 'lima', 4]

In [17]:
a[1]= 5

In [18]:
a

[1, 5, 4, 'empat', 'lima', 4]

In [19]:
b= []

In [20]:
b.append(1)

In [21]:
b

[1]

In [22]:
b.append(2)

In [23]:
b

[1, 2]

# Slicing
memotong
* inclusive : exclusive : step

In [24]:
a = [0, 1, 2, 3, 4, 5, 6]

In [25]:
a[0:5]

[0, 1, 2, 3, 4]

In [26]:
a[1:3]

[1, 2]

In [27]:
a [:-1]

[0, 1, 2, 3, 4, 5]

In [28]:
a[:-2]

[0, 1, 2, 3, 4]

In [30]:
a[::2]

[0, 2, 4, 6]

In [31]:
a[:5:2]

[0, 2, 4]

In [32]:
a[::-1]

[6, 5, 4, 3, 2, 1, 0]

# join & split

In [33]:
a = ['cat', 'fish', 'dog']

In [34]:
", ".join(a)

'cat, fish, dog'

In [35]:
" ".join(a)

'cat fish dog'

In [42]:
a= "Ir Rahmat Aldino, S.T, M.T"

In [43]:
a= a.split(",")
a

['Ir Rahmat Aldino', ' S.T', ' M.T']

In [40]:
a[1:]

[' S.T', ' M.T']

# Dictionary
{key : value}

In [44]:
a = {"cat": "kucing", "dog":"anjing", "fish": "ikan"}

In [45]:
a

{'cat': 'kucing', 'dog': 'anjing', 'fish': 'ikan'}

In [46]:
a["elephant"]= "gajah"

In [47]:
a

{'cat': 'kucing', 'dog': 'anjing', 'fish': 'ikan', 'elephant': 'gajah'}

In [48]:
a["cat"]

'kucing'

In [49]:
a["dog"]

'anjing'

In [50]:
a.keys()

dict_keys(['cat', 'dog', 'fish', 'elephant'])

In [51]:
a.values()

dict_values(['kucing', 'anjing', 'ikan', 'gajah'])

In [52]:
a["cat"] = 1

In [53]:
a

{'cat': 1, 'dog': 'anjing', 'fish': 'ikan', 'elephant': 'gajah'}

# fungsi

In [56]:
import math

In [54]:
def pengurangan (a,b):
    return a-b

In [55]:
pengurangan(1000,879)

121

In [63]:
def knn (data_testing, X_train, y_train):
    return math.sqrt((data_testing-X_train)**2-(y_train-X_train)**2)

In [66]:
knn(100,30,50)

67.08203932499369

# Conditionals

In [67]:
nilai = 73

In [68]:
if 0<= nilai <50:
    print ("nilai nya C")
elif 50<= nilai <75:
    print ("nilai nya B")
elif 75<= nilai <100:
    print ("nilai nya A")
elif nilai == 100:
    print ("nilai nya S")
else:
    print ("nilainya ngaco")

nilai nya A


In [69]:
def konversi_ke_indeks (nilai):
    if 0<= nilai <50:
        return ("nilai nya C")
    elif 50<= nilai <75:
        return ("nilai nya B")
    elif 75<= nilai <100:
        return ("nilai nya A")
    elif nilai == 100:
        return ("nilai nya S")
    else:
        return ("nilainya ngaco")

In [70]:
konversi_ke_indeks(45)

'nilai nya C'

# Iterations
* menelusuri tiap data yang ada

In [71]:
numbers=[1,3,4,5,6]

In [73]:
for i in numbers:
    print (i)

1
3
4
5
6


In [76]:
for i in (10, 40, 17,80,99):
    print(konversi_ke_indeks(i))

nilai nya C
nilai nya C
nilai nya C
nilai nya A
nilai nya A


In [77]:
for i in range (1,15):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [80]:
a.keys()

dict_keys(['cat', 'dog', 'fish', 'elephant'])

In [82]:
for key in a.keys():
    print(a[key])

1
anjing
ikan
gajah


In [83]:
for key in a.keys():
    print("Bahasa Indonesia nya",key,"adalah",a[key])

Bahasa Indonesia nya cat adalah 1
Bahasa Indonesia nya dog adalah anjing
Bahasa Indonesia nya fish adalah ikan
Bahasa Indonesia nya elephant adalah gajah


In [85]:
for key in a.keys():
    print(f"Bahasa Indonesia nya {key} adalah {a[key]}")

Bahasa Indonesia nya cat adalah 1
Bahasa Indonesia nya dog adalah anjing
Bahasa Indonesia nya fish adalah ikan
Bahasa Indonesia nya elephant adalah gajah


In [86]:
a = []
for i in range (1, 20):
    a.append(i)

In [87]:
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

# Python Comprehansion

In [88]:
a = [i for i in range (1,20)]

In [89]:
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [90]:
a = [i**2 for i in range (20)]

In [91]:
a

[0,
 1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361]

In [92]:
a = {i: i**2for i in range (10)}
a

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}

In [ ]:
nilai = [konversi_ke_indeks(i)for i in (29, 49, 49, 95 , 93, 1010,-0.21)]
nilai

In [94]:
for i in range (1,21):
    if i>18:
        print(18)
    else:
        print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
18
18


In [95]:
for i in range (1,21):
    print(min(i,18))

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
18
18


In [1]:
for i in range (1,21):
    print(i)
    if i == 18:
        break

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18


In [6]:
id()

NameError: name 'angka' is not defined

# numerical in python

In [32]:
import numpy as np

In [20]:
a = [(1,3,5,56,6),
    (6,5,43,3,2)]
a

[(1, 3, 5, 56, 6), (6, 5, 43, 3, 2)]

In [17]:
b = np.array(a)
b

array([[ 1,  3,  5, 56,  6],
       [ 6,  5, 43,  3,  2]])

In [22]:
b[1,1] = (100)
b

array([[  1,   3,   5,  56,   6],
       [  6, 100,  43,   3,   2]])

In [5]:
a = range(20)

In [6]:
a

range(0, 20)

In [23]:
a = [1,2,3,4,5,6,7,8,9,10]
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [24]:
b = a[0:2]
print(b)
c = a[-2:]
print(c)

[1, 2]
[9, 10]


In [25]:
d = [] 
d.append(c)
d.append(b)

In [26]:
print(d)

[[9, 10], [1, 2]]


In [27]:
a = range(1,20)

print(a)

range(1, 20)


In [30]:
[i for i in range (1,20)]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [33]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])